//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoki_Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinanceSet
    {
        public int Id { get; set; }
        public Nullable<int> Gain { get; set; }
        public Nullable<int> Costs { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
