//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zoki_Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Zoki_ProjectEntities1 : DbContext
    {
        public Zoki_ProjectEntities1()
            : base("name=Zoki_ProjectEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientSet> ClientSet { get; set; }
        public virtual DbSet<CompositionSet> CompositionSet { get; set; }
        public virtual DbSet<CustomSet> CustomSet { get; set; }
        public virtual DbSet<FinanceSet> FinanceSet { get; set; }
        public virtual DbSet<HotelSet> HotelSet { get; set; }
        public virtual DbSet<PersonalSet> PersonalSet { get; set; }
        public virtual DbSet<ProductSet> ProductSet { get; set; }
        public virtual DbSet<ProviderSet> ProviderSet { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
